//
// Copyright (C) 2026 IOTech Ltd
//

package prts

import (
	"fmt"
	"strings"
)

// objectTypeMap maps BACnet object type IDs to human-readable names.
// Definitions sourced from https://github.com/bacnet-stack/bacnet-stack/blob/bacnet-stack-1.0/src/bacnet/bacenum.h#L1179-L1252
var objectTypeMap = map[int]string{
	0:  "Analog Input",
	1:  "Analog Output",
	2:  "Analog Value",
	3:  "Binary Input",
	4:  "Binary Output",
	5:  "Binary Value",
	6:  "Calendar",
	7:  "Command",
	8:  "Device",
	9:  "Event Enrollment",
	10: "File",
	11: "Group",
	12: "Loop",
	13: "Multi State Input",
	14: "Multi State Output",
	15: "Notification Class",
	16: "Program",
	17: "Schedule",
	18: "Averaging",
	19: "Multi State Value",
	20: "Trendlog",
	21: "Life Safety Point",
	22: "Life Safety Zone",
	23: "Accumulator",
	24: "Pulse Converter",
	25: "Event Log",
	26: "Global Group",
	27: "Trend Log Multiple",
	28: "Load Control",
	29: "Structured View",
	30: "Access Door",
	31: "Timer",
	32: "Access Credential",
	33: "Access Point",
	34: "Access Rights",
	35: "Access User",
	36: "Access Zone",
	37: "Credential Data Input",
	38: "Network Security",
	39: "Bitstring Value",
	40: "Characterstring Value",
	41: "Date Pattern Value",
	42: "Date Value",
	43: "Datetime Pattern Value",
	44: "Datetime Value",
	45: "Integer Value",
	46: "Large Analog Value",
	47: "Octetstring Value",
	48: "Positive Integer Value",
	49: "Time Pattern Value",
	50: "Time Value",
	51: "Notification Forwarder",
	52: "Alert Enrollment",
	53: "Channel",
	54: "Lighting Output",
	55: "Binary Lighting Output",
	56: "Network Port",
	57: "Elevator Group",
	58: "Escalator",
	59: "Lift",
	60: "Staging",
}

// BACnet object type range constants.
// Enumerated values 0-127 are reserved for definition by ASHRAE.
// Enumerated values 128-1023 may be used by others subject to the procedures and constraints described in Clause 23.
// Refer: https://github.com/bacnet-stack/bacnet-stack/blob/bacnet-stack-1.0/src/bacnet/bacenum.h#L1242-L1247
const (
	ObjectProprietaryMin = 128
	MaxObjectType        = 1024
	ObjectTypeNone       = 65535 // 0xFFFFu — sentinel value defined by the BACnet spec
	ObjectTypeNoneString = "None"
)

// propertyStringMap maps BACnet property IDs to normalized names (lowercase with underscores).
// Definitions sourced from https://github.com/stargieg/bacnet-stack/blob/56034b7b11f53efba749a162447a71d10b6fcc3a/include/bacenum.h#L27-L530
var propertyStringMap = map[int]string{
	0:   "acked_transitions",
	1:   "ack_required",
	2:   "action",
	3:   "action_text",
	4:   "active_text",
	5:   "active_vt_sessions",
	6:   "alarm_value",
	7:   "alarm_values",
	8:   "all",
	9:   "all_writes_successful",
	10:  "apdu_segment_timeout",
	11:  "apdu_timeout",
	12:  "application_software_version",
	13:  "archive",
	14:  "bias",
	15:  "change_of_state_count",
	16:  "change_of_state_time",
	17:  "notification_class",
	18:  "blank_1",
	19:  "controlled_variable_reference",
	20:  "controlled_variable_units",
	21:  "controlled_variable_value",
	22:  "cov_increment",
	23:  "date_list",
	24:  "daylight_savings_status",
	25:  "deadband",
	26:  "derivative_constant",
	27:  "derivative_constant_units",
	28:  "description",
	29:  "description_of_halt",
	30:  "device_address_binding",
	31:  "device_type",
	32:  "effective_period",
	33:  "elapsed_active_time",
	34:  "error_limit",
	35:  "event_enable",
	36:  "event_state",
	37:  "event_type",
	38:  "exception_schedule",
	39:  "fault_values",
	40:  "feedback_value",
	41:  "file_access_method",
	42:  "file_size",
	43:  "file_type",
	44:  "firmware_revision",
	45:  "high_limit",
	46:  "inactive_text",
	47:  "in_process",
	48:  "instance_of",
	49:  "integral_constant",
	50:  "integral_constant_units",
	51:  "issue_confirmed_notifications",
	52:  "limit_enable",
	53:  "list_of_group_members",
	54:  "list_of_object_property_references",
	55:  "list_of_session_keys",
	56:  "local_date",
	57:  "local_time",
	58:  "location",
	59:  "low_limit",
	60:  "manipulated_variable_reference",
	61:  "maximum_output",
	62:  "max_apdu_length_accepted",
	63:  "max_info_frames",
	64:  "max_master",
	65:  "max_pres_value",
	66:  "minimum_off_time",
	67:  "minimum_on_time",
	68:  "minimum_output",
	69:  "min_pres_value",
	70:  "model_name",
	71:  "modification_date",
	72:  "notify_type",
	73:  "number_of_apdu_retries",
	74:  "number_of_states",
	75:  "object_identifier",
	76:  "object_list",
	77:  "object_name",
	78:  "object_property_reference",
	79:  "object_type",
	80:  "optional",
	81:  "out_of_service",
	82:  "output_units",
	83:  "event_parameters",
	84:  "polarity",
	85:  "present_value",
	86:  "priority",
	87:  "priority_array",
	88:  "priority_for_writing",
	89:  "process_identifier",
	90:  "program_change",
	91:  "program_location",
	92:  "program_state",
	93:  "proportional_constant",
	94:  "proportional_constant_units",
	95:  "protocol_conformance_class",
	96:  "protocol_object_types_supported",
	97:  "protocol_services_supported",
	98:  "protocol_version",
	99:  "read_only",
	100: "reason_for_halt",
	101: "recipient",
	102: "recipient_list",
	103: "reliability",
	104: "relinquish_default",
	105: "required",
	106: "resolution",
	107: "segmentation_supported",
	108: "setpoint",
	109: "setpoint_reference",
	110: "state_text",
	111: "status_flags",
	112: "system_status",
	113: "time_delay",
	114: "time_of_active_time_reset",
	115: "time_of_state_count_reset",
	116: "time_synchronization_recipients",
	117: "units",
	118: "update_interval",
	119: "utc_offset",
	120: "vendor_identifier",
	121: "vendor_name",
	122: "vt_classes_supported",
	123: "weekly_schedule",
	124: "attempted_samples",
	125: "average_value",
	126: "buffer_size",
	127: "client_cov_increment",
	128: "cov_resubscription_interval",
	129: "current_notify_time",
	130: "event_time_stamps",
	131: "log_buffer",
	132: "log_device_object_property",
	133: "enable",
	134: "log_interval",
	135: "maximum_value",
	136: "minimum_value",
	137: "notification_threshold",
	138: "previous_notify_time",
	139: "protocol_revision",
	140: "records_since_notification",
	141: "record_count",
	142: "start_time",
	143: "stop_time",
	144: "stop_when_full",
	145: "total_record_count",
	146: "valid_samples",
	147: "window_interval",
	148: "window_samples",
	149: "maximum_value_timestamp",
	150: "minimum_value_timestamp",
	151: "variance_value",
	152: "active_cov_subscriptions",
	153: "backup_failure_timeout",
	154: "configuration_files",
	155: "database_revision",
	156: "direct_reading",
	157: "last_restore_time",
	158: "maintenance_required",
	159: "member_of",
	160: "mode",
	161: "operation_expected",
	162: "setting",
	163: "silenced",
	164: "tracking_value",
	165: "zone_members",
	166: "life_safety_alarm_values",
	167: "max_segments_accepted",
	168: "profile_name",
	169: "auto_slave_discovery",
	170: "manual_slave_address_binding",
	171: "slave_address_binding",
	172: "slave_proxy_enable",
	173: "last_notify_record",
	174: "schedule_default",
	175: "accepted_modes",
	176: "adjust_value",
	177: "count",
	178: "count_before_change",
	179: "count_change_time",
	180: "cov_period",
	181: "input_reference",
	182: "limit_monitoring_interval",
	183: "logging_object",
	184: "logging_record",
	185: "prescale",
	186: "pulse_rate",
	187: "scale",
	188: "scale_factor",
	189: "update_time",
	190: "value_before_change",
	191: "value_set",
	192: "value_change_time",
	193: "align_intervals",
	195: "interval_offset",
	196: "last_restart_reason",
	197: "logging_type",
	202: "restart_notification_recipients",
	203: "time_of_device_restart",
	204: "time_synchronization_interval",
	205: "trigger",
	206: "utc_time_synchronization_recipients",
	207: "node_subtype",
	208: "node_type",
	209: "structured_object_list",
	210: "subordinate_annotations",
	211: "subordinate_list",
	212: "actual_shed_level",
	213: "duty_window",
	214: "expected_shed_level",
	215: "full_duty_baseline",
	218: "requested_shed_level",
	219: "shed_duration",
	220: "shed_level_descriptions",
	221: "shed_levels",
	222: "state_description",
	226: "door_alarm_state",
	227: "door_extended_pulse_time",
	228: "door_members",
	229: "door_open_too_long_time",
	230: "door_pulse_time",
	231: "door_status",
	232: "door_unlock_delay_time",
	233: "lock_status",
	234: "masked_alarm_values",
	235: "secured_status",
	244: "absentee_limit",
	245: "access_alarm_events",
	246: "access_doors",
	247: "access_event",
	248: "access_event_authentication_factor",
	249: "access_event_credential",
	250: "access_event_time",
	251: "access_transaction_events",
	252: "accompaniment",
	253: "accompaniment_time",
	254: "activation_time",
	255: "active_authentication_policy",
	256: "assigned_access_rights",
	257: "authentication_factors",
	258: "authentication_policy_list",
	259: "authentication_policy_names",
	260: "authentication_status",
	261: "authorization_mode",
	262: "belongs_to",
	263: "credential_disable",
	264: "credential_status",
	265: "credentials",
	266: "credentials_in_zone",
	267: "days_remaining",
	268: "entry_points",
	269: "exit_points",
	270: "expiration_time",
	271: "extended_time_enable",
	272: "failed_attempt_events",
	273: "failed_attempts",
	274: "failed_attempts_time",
	275: "last_access_event",
	276: "last_access_point",
	277: "last_credential_added",
	278: "last_credential_added_time",
	279: "last_credential_removed",
	280: "last_credential_removed_time",
	281: "last_use_time",
	282: "lockout",
	283: "lockout_relinquish_time",
	284: "master_exemption",
	285: "max_failed_attempts",
	286: "members",
	287: "muster_point",
	288: "negative_access_rules",
	289: "number_of_authentication_policies",
	290: "occupancy_count",
	291: "occupancy_count_adjust",
	292: "occupancy_count_enable",
	293: "occupancy_exemption",
	294: "occupancy_lower_limit",
	295: "occupancy_lower_limit_enforced",
	296: "occupancy_state",
	297: "occupancy_upper_limit",
	298: "occupancy_upper_limit_enforced",
	299: "passback_exemption",
	300: "passback_mode",
	301: "passback_timeout",
	302: "positive_access_rules",
	303: "reason_for_disable",
	304: "supported_formats",
	305: "supported_format_classes",
	306: "threat_authority",
	307: "threat_level",
	308: "trace_flag",
	309: "transaction_notification_class",
	310: "user_external_identifier",
	311: "user_information_reference",
	317: "user_name",
	318: "user_type",
	319: "uses_remaining",
	320: "zone_from",
	321: "zone_to",
	322: "access_event_tag",
	323: "global_identifier",
	326: "verification_time",
	327: "base_device_security_policy",
	328: "distribution_key_revision",
	329: "do_not_hide",
	330: "key_sets",
	331: "last_key_server",
	332: "network_access_security_policies",
	333: "packet_reorder_time",
	334: "security_pdu_timeout",
	335: "security_time_window",
	336: "supported_security_algorithm",
	337: "update_key_set_timeout",
	338: "backup_and_restore_state",
	339: "backup_preparation_time",
	340: "restore_completion_time",
	341: "restore_preparation_time",
	342: "bit_mask",
	343: "bit_text",
	344: "is_utc",
	345: "group_members",
	346: "group_member_names",
	347: "member_status_flags",
	348: "requested_update_interval",
	349: "covu_period",
	350: "covu_recipients",
	351: "event_message_texts",
	352: "event_message_texts_config",
	353: "event_detection_enable",
	354: "event_algorithm_inhibit",
	355: "event_algorithm_inhibit_ref",
	356: "time_delay_normal",
	357: "reliability_evaluation_inhibit",
	358: "fault_parameters",
	359: "fault_type",
	360: "local_forwarding_only",
	361: "process_identifier_filter",
	362: "subscribed_recipients",
	363: "port_filter",
	364: "authorization_exemptions",
	365: "allow_group_delay_inhibit",
	366: "channel_number",
	367: "control_groups",
	368: "execution_delay",
	369: "last_priority",
	370: "write_status",
	371: "property_list",
	372: "serial_number",
	373: "blink_warn_enable",
	374: "default_fade_time",
	375: "default_ramp_rate",
	376: "default_step_increment",
	377: "egress_time",
	378: "in_progress",
	379: "instantaneous_power",
	380: "lighting_command",
	381: "lighting_command_default_priority",
	382: "max_actual_value",
	383: "min_actual_value",
	384: "power",
	385: "transition",
	386: "egress_active",
	387: "interface_value",
	388: "fault_high_limit",
	389: "fault_low_limit",
	390: "low_diff_limit",
	391: "strike_count",
	392: "time_of_strike_count_reset",
	393: "default_timeout",
	394: "initial_timeout",
	395: "last_state_change",
	396: "state_change_values",
	397: "timer_running",
	398: "timer_state",
	399: "apdu_length",
	400: "ip_address",
	401: "ip_default_gateway",
	402: "ip_dhcp_enable",
	403: "ip_dhcp_lease_time",
	404: "ip_dhcp_lease_time_remaining",
	405: "ip_dhcp_server",
	406: "ip_dns_server",
	407: "bacnet_ip_global_address",
	408: "bacnet_ip_mode",
	409: "bacnet_ip_multicast_address",
	410: "bacnet_ip_nat_traversal",
	411: "ip_subnet_mask",
	412: "bacnet_ip_udp_port",
	413: "bbmd_accept_fd_registrations",
	414: "bbmd_broadcast_distribution_table",
	415: "bbmd_foreign_device_table",
	416: "changes_pending",
	417: "command",
	418: "fd_bbmd_address",
	419: "fd_subscription_lifetime",
	420: "link_speed",
	421: "link_speeds",
	422: "link_speed_autonegotiate",
	423: "mac_address",
	424: "network_interface_name",
	425: "network_number",
	426: "network_number_quality",
	427: "network_type",
	428: "routing_table",
	429: "virtual_mac_address_table",
	430: "command_time_array",
	431: "current_command_priority",
	432: "last_command_time",
	433: "value_source",
	434: "value_source_array",
	435: "bacnet_ipv6_mode",
	436: "ipv6_address",
	437: "ipv6_prefix_length",
	438: "bacnet_ipv6_udp_port",
	439: "ipv6_default_gateway",
	440: "bacnet_ipv6_multicast_address",
	441: "ipv6_dns_server",
	442: "ipv6_auto_addressing_enable",
	443: "ipv6_dhcp_lease_time",
	444: "ipv6_dhcp_lease_time_remaining",
	445: "ipv6_dhcp_server",
	446: "ipv6_zone_index",
	447: "assigned_landing_calls",
	448: "car_assigned_direction",
	449: "car_door_command",
	450: "car_door_status",
	451: "car_door_text",
	452: "car_door_zone",
	453: "car_drive_status",
	454: "car_load",
	455: "car_load_units",
	456: "car_mode",
	457: "car_moving_direction",
	458: "car_position",
	459: "elevator_group",
	460: "energy_meter",
	461: "energy_meter_ref",
	462: "escalator_mode",
	463: "fault_signals",
	464: "floor_text",
	465: "group_id",
	467: "group_mode",
	468: "higher_deck",
	469: "installation_id",
	470: "landing_calls",
	471: "landing_call_control",
	472: "landing_door_status",
	473: "lower_deck",
	474: "machine_room_id",
	475: "making_car_call",
	476: "next_stopping_floor",
	477: "operation_direction",
	478: "passenger_alarm",
	479: "power_mode",
	480: "registered_car_call",
	481: "active_cov_multiple_subscriptions",
	482: "protocol_level",
	483: "reference_port",
	484: "deployed_profile_location",
	485: "profile_location",
	486: "tags",
	487: "subordinate_node_types",
	488: "subordinate_tags",
	489: "subordinate_relationships",
	490: "default_subordinate_relationship",
	491: "represents",
}

// GetBACnetObjectTypeName returns the human-readable string for a BACnet object type ID.
func GetBACnetObjectTypeName(objectType int) (string, error) {
	if objectType < 0 {
		return "", fmt.Errorf("object type %d is invalid", objectType)
	}
	if objectType == ObjectTypeNone {
		return ObjectTypeNoneString, nil
	}
	if objectType >= MaxObjectType {
		return "", fmt.Errorf("object type %d exceeds max BACnet object limit", objectType)
	}

	if objectTypeStr, ok := objectTypeMap[objectType]; ok {
		return objectTypeStr, nil
	}

	// Values 128-1023 are proprietary, defined by vendors per Clause 23
	if objectType >= ObjectProprietaryMin {
		return fmt.Sprintf("Proprietary Type (%d)", objectType), nil
	}

	// Values 0-127 not in the map are reserved by ASHRAE but not yet defined
	return fmt.Sprintf("Reserved Type (%d)", objectType), nil
}

// GetBACnetObjectTypeString returns the BACnet object type name for use in DTOs.
// The name is all lowercase with spaces replaced by underscores (e.g. "analog_input").
func GetBACnetObjectTypeString(objectType int) (string, error) {
	name, err := GetBACnetObjectTypeName(objectType)
	if err != nil {
		return "", err
	}
	return strings.ToLower(strings.ReplaceAll(name, " ", "_")), nil
}

// GetBACnetPropertyString returns the normalized name for a BACnet property ID.
// The name is all lowercase with underscores (e.g. "present_value").
func GetBACnetPropertyString(propertyID int) (string, error) {
	if propertyID < 0 {
		return "", fmt.Errorf("property ID %d is invalid", propertyID)
	}
	if name, ok := propertyStringMap[propertyID]; ok {
		return name, nil
	}
	return fmt.Sprintf("%d", propertyID), nil
}
